fix: specify type better for context arg in defaultErrorFormatter (#690)
* fix: specify type better for context 

When context is null for example, it crashes with a type error
```
TypeError: Cannot read property 'reply' of null
    at AsyncFunction.defaultErrorFormatter (/home/capaj/work-repos/authier-repos/authier/node_modules/mercurius/lib/errors.js:67:19)
```

* test: add specs for new types