Fix TypeError: this.queue.close is not a function (#93)
* Fix TypeError: this.queue.close is not a function

In some rare cases there's a possibility when `close` will be called before `subscribe` will happen. In this case that error could cause even app server crash. Also it prevents `this.queue.destroy()` to be called.

I don't know how to properly test this case, cause it's caused by some abnormal behaviour of client side. Tried some options with closing ws client right after establishing connection, sending some crappy staff into it - nothing caused this bug to appear.
Anyway it's present and needed to be fixed.

* fix: ignore coverage

* chore: add comments

* test: add test